#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Edición digital Salve Regina
email: suarezg106@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  En el marco del curso de Edición digital del Pregrado en Literatura de la Universidad EAFIT, los estudiantes de los semestres 2021-2 y 2022-1 realizaron este proyecto de edición digital recuperando el material patrimonial de Tomás Carrasquilla ubicado en la Biblioteca Luis Echavarría Villegas. 
baseurl: "/edicionsalveregina" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Color scheme. Options: red, orange, magenta, cyan, blue, brown
color-scheme:

# Permalinks
permalink: pretty
permalink: /:title/

# Set encoding to UTF-8
encoding: utf-8

# This is to keep things tidy.
include: ['_pages']

# Exclude from processing.
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor
